fix: preliminary writing style fix
lcpu-club/getting-started pull request #26
Opened 2024-11-11 13:05 UTC by djdjz7

may need further modifications after agreeing up the writing guidelines.

2024-11-11 13:45 UTC, HolgerHuo commented on pnpm-lock.yaml
This update seems unnecessary to me.

2024-11-11 13:47 UTC, HolgerHuo commented on basic/11-linux-basic-2.md
> +在 Linux 系统中 root 账户拥有最高权限，你所选择的发行版在安装时可能会要求设置 root 账户密码。如果没有这一选项可以在安装系统后在终端使用 passwd 命令设置。
We can change passwd to `passwd`

2024-11-11 13:50 UTC, 000lbh requested changes

2024-11-11 13:50 UTC, 000lbh commented on basic/08-drive-your-computer-4.md
> +他把 "Doc1.docx" 直接重命名成了 "实验报告"！他连后缀名都删干净了！现在他再也找不到打开这份文档的方法了！
用中文引号

2024-11-11 13:50 UTC, 000lbh commented on basic/08-drive-your-computer-4.md
> +他需要下载一个腾讯视频！他在视频网页点击了“下载”，浏览器开始下载腾讯视频客户端了！他开始安装了！他在客户端里下载了一个 .qlv 格式的文件！他直接把这个文件发给别人了！
`.qlv`

2024-11-12 06:57 UTC, 000lbh approved these changes

2024-11-13 23:49 UTC, HolgerHuo approved these changes

2024-11-14 00:15 UTC, merged