doc: added macos shortcuts
lcpu-club/getting-started pull request #28
Opened 2024-11-13 06:15 UTC by djdjz7

2024-11-13 06:28 UTC, 000lbh submitted a review, later dismissed

2024-11-16 05:48 UTC, leavelet requested changes
还可以提一下符号与文字的对应，比如⌘对应command之类的

2024-11-16 05:48 UTC, leavelet commented on basic/07-drive-your-computer-3.md
> +  - 一般情况下，撤销对应的快捷键是 `Command+Shift+Z`，但是在某些第三方程序，例如 Microsoft Word 中，`Command+Z` 也可以用于撤销。
这里确定没错吗，一般情况下撤销就是 command+z 吧？

2024-11-16 06:32 UTC, djdjz7 commented
> 还可以提一下符号与文字的对应，比如⌘对应command之类的

这几个字符跨平台显示效果不太好，我准备画几个svg上去试一试

2024-11-16 06:33 UTC, djdjz7 commented on basic/07-drive-your-computer-3.md
> +  - 一般情况下，撤销对应的快捷键是 `Command+Shift+Z`，但是在某些第三方程序，例如 Microsoft Word 中，`Command+Z` 也可以用于撤销。
嘶写错了抱歉，这里是重做有问题

2024-11-18 00:13 UTC, HolgerHuo commented
Vue part looks good to me. But maybe we should consider make it global or consider some other ways of implementing this feature, e.g., plain svg files with global css, or special unicode font, so as to enable other features, like pdf version of this lecture, publishing to other platforms.

2024-11-18 00:14 UTC, HolgerHuo commented on basic/07-drive-your-computer-3.md
> +  - 一般情况下，重做对应的快捷键是 `Command+Shift+Z`，但是在某些第三方程序，例如 Microsoft Word 中，`Command+Y` 也可以用于重做。
This line is unfixed yet.

2024-11-18 00:17 UTC, HolgerHuo commented
I'm unfamiliar with macos shortcuts part. I'll approve now for vue part, macos part should be reviewed otherwise.

2024-11-18 00:18 UTC, HolgerHuo approved these changes

2024-11-18 00:55 UTC, 000lbh approved these changes

2024-11-18 00:56 UTC, leavelet approved these changes

2024-11-18 00:58 UTC, merged